In [62]:
import pandas as pd
import ast
import numpy as np

In [120]:
data = pd.read_csv('data/target.csv')

data.set_index("CensusTract", inplace =True)

### HEALTHY FOODS

In [121]:
healthy = pd.read_csv('data/census_healthy1.csv',index_col='Unnamed: 0')

healthy['sentiment']=healthy['sentiment'].apply(ast.literal_eval)

healthy['comp']=healthy['sentiment'].apply(lambda x: x['compound'])

sub_healthy = healthy[['keyword','text','coords','lat','long','census','comp']]

sh_groupby = sub_healthy.groupby("census")

avg_sent = sh_groupby.mean()

joined_healthy = data.join(avg_sent)

joined_healthy[~joined_healthy['lat'].isnull()].groupby('LILATracts_1And10').mean()

                         lat       long      comp
LILATracts_1And10
0                  37.312872 -92.654379  0.294027
1                  36.167204 -90.754764  0.299744

In [155]:
(joined_healthy['LILATracts_1And10']==1).sum()

9245

In [145]:
joined_data = data.join(sub_healthy.set_index('census'))

In [157]:
joined_data.to_csv('data/joined_data.csv')

### UNHEALTHY FOODS

In [122]:
unhealthy = pd.read_csv('data/census_unhealthy1.csv',index_col='Unnamed: 0')

unhealthy['sentiment']=unhealthy['sentiment'].apply(ast.literal_eval)

unhealthy['comp']=unhealthy['sentiment'].apply(lambda x: x['compound'])

sub_unhealthy = unhealthy[['keyword','text','coords','lat','long','census','comp']]

suh_groupby = sub_unhealthy.groupby("census")

avg_sent_uh = suh_groupby.mean()

joined_unhealthy = data.join(avg_sent_uh)

joined_unhealthy[~joined_unhealthy['lat'].isnull()].groupby('LILATracts_1And10').mean()

                         lat       long      comp
LILATracts_1And10
0                  37.331388 -92.855605  0.300909
1                  35.909347 -92.017618  0.334915

### GROCERY STORES

In [123]:
grocery = pd.read_csv("data/census_grocery1.csv",index_col='Unnamed: 0')

grocery['sentiment']=grocery['sentiment'].apply(ast.literal_eval)

grocery['comp']=grocery['sentiment'].apply(lambda x: x['compound'])

sub_grocery = grocery[['keyword','text','coords','lat','long','census','comp']]

grocery_groupby = sub_grocery.groupby("census")

avg_sent_grocery = grocery_groupby.mean()

joined_grocery = data.join(avg_sent_grocery)

joined_grocery[~joined_grocery['lat'].isnull()].groupby('LILATracts_1And10').mean()

                         lat        long      comp
LILATracts_1And10
0                  36.144861 -101.187810  0.233442
1                  36.828097 -102.679108  0.408850

### FAST FOODS

In [124]:
fastfood = pd.read_csv("data/census_fastfood1.csv",index_col='Unnamed: 0')

fastfood['sentiment']=fastfood['sentiment'].apply(ast.literal_eval)

fastfood['comp']=fastfood['sentiment'].apply(lambda x: x['compound'])

sub_fastfood = fastfood[['keyword','text','coords','lat','long','census','comp']]

fastfood_groupby = sub_fastfood.groupby("census")

avg_sent_fastfood = fastfood_groupby.mean()

joined_fastfood = data.join(avg_sent_fastfood)

joined_fastfood[~joined_fastfood['lat'].isnull()].groupby('LILATracts_1And10').mean()

                         lat       long      comp
LILATracts_1And10
0                  37.591433 -93.645818  0.321130
1                  37.352193 -93.893184  0.326516

In [130]:
joined_fastfood[joined_fastfood['comp']<0]

             LILATracts_1And10        lat        long      comp
CensusTract
4013116704                   0  33.374326 -111.971831 -0.271400
6013369001                   0  37.954464 -122.331994 -0.551200
6021010100                   1  39.748840 -122.204605 -0.170600
6037310601                   0  34.187468 -118.318416 -0.051350
6037401202                   0  34.110854 -117.827525 -0.033100
6037543202                   0  33.876877 -118.222920 -0.144400
6037980028                   0  33.937937 -118.392896 -0.070650
6061020604                   0  38.744174 -121.223571 -0.051600
6075010100                   0  37.807750 -122.418554 -0.361200
9009351400                   0  41.543634  -73.035669 -0.381800
11001007100                  0  38.880182  -76.986718 -0.226300
11001010600                  0  38.903574  -77.005786 -0.175200
12011041200                  0  26.139553  -80.202067 -0.493900
12031012200                  1  30.304310  -81.754706 -0.701900
12033002605                  0  30.380326  -87.356256 -0.807400
12057005301                  0  27.948881  -82.448337 -0.603700
12085000400                  0  27.243725  -80.271054 -0.089150
12086004000                  0  25.813344  -80.128603 -0.388100
12086006702                  0  25.762793  -80.192760 -0.273200
12086007001                  0  25.749312  -80.254264 -0.362600
12105010701                  0  28.016011  -81.957925 -0.464200
12127082802                  0  29.036160  -80.931270 -0.340400
13245010400                  0  33.447900  -82.006700 -0.528200
15009031404                  1  20.872311 -156.676402 -0.033167
15009031503                  0  20.920598 -156.695089 -0.476700
18089041600                  1  41.551190  -87.271760 -0.381800
18097391000                  0  39.769200  -86.158200 -0.464800
23031038001                  0  43.111571  -70.733562 -0.735100
24003751102                  0  39.193104  -76.606658 -0.118650
25003911100                  0  42.494761  -73.206754 -0.051600
26025001800                  0  42.260360  -85.199195 -0.380200
26111290900                  0  43.642202  -84.245299 -0.598300
26163579900                  0  42.314600  -83.216600 -0.765000
27037060102                  0  44.916100  -93.101400 -0.421500
32003005322                  0  36.021386 -115.118128 -0.296000
34017007400                  0  40.714883  -74.034162 -0.273200
34023007600                  0  40.483710  -74.280000 -0.077200
34041031500                  0  40.821304  -74.836845 -0.421500
35049001202                  0  35.654604 -105.996650 -0.354000
36047003500                  0  40.684052  -73.977160 -0.340000
36061016300                  0  40.782378  -73.981096 -0.458800
36061019600                  0  40.804408  -73.937476 -0.249050
36081025302                  0  40.743892  -73.913527 -0.246950
36085022600                  0  40.521643  -74.235587 -0.482600
39009973901                  1  39.327004  -82.100715 -0.025800
39035132301                  1  41.395355  -81.550152 -0.744000
39103416000                  0  41.237836  -81.807155 -0.296000
39113050104                  0  39.637333  -84.219197 -0.280800
40027202206                  0  35.319335  -97.497129 -0.171350
40143007503                  0  36.036300  -95.783600 -0.476700
41067031616                  0  45.534664 -122.876827 -0.153100
47157022130                  1  35.006400  -90.024900 -0.817600
48001950800                  0  31.733781  -95.610918 -0.205700
48029131000                  0  29.423710  -98.405173 -0.413500
48113016100                  1  32.715300  -97.016900 -0.595100
48209010200                  0  29.888565  -97.939606 -0.521600
48479000200                  0  27.506000  -99.493800 -0.250000
51600300500                  0  38.841790  -77.308880 -0.273200
51683910302                  0  38.751056  -77.471344 -0.361200
53033005302                  0  47.655742 -122.308710 -0.248100

In [129]:
joined_fastfood.index.unique()

Int64Index([ 1001020100,  1001020200,  1001020300,  1001020400,  1001020500,
             1001020600,  1001020700,  1001020801,  1001020802,  1001020900,
            ...
            56039967702, 56039967800, 56041975200, 56041975300, 56041975400,
            56043000200, 56043000301, 56043000302, 56045951100, 56045951300],
           dtype='int64', name='CensusTract', length=72864)